name: "Docs bug report"
description: "Report a broken link, typo, or outdated example in the FHEVM docs."
title: "[docs] <short summary>"
labels:
  - documentation
body:
  - type: input
    id: docs_page
    attributes:
      label: Affected page or URL
      description: Link to the docs page, tutorial, or markdown file.
      placeholder: "https://docs.zama.ai/... or docs/path/file.md"
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: What is wrong?
      description: Describe the problem (broken link, command that fails, outdated instructions, etc.).
      placeholder: "The setup-hardhat guide fails at step X because..."
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: List the steps you took that led to the problem.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node.js version, package manager and any other relevant details.
      placeholder: "macOS 15, Node 22, pnpm 9, hardhat 3..."
    validations:
      required: false
